app:
  name: "My Redis App"
  env: "development"
  port: 8080

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
  pool_size: 10

kafka:
  brokers:
    - "kafka-0:9092"
    - "kafka-1:9092"
  topic: "url-events"
  write_timeout: "3s"
  batch_size: 500
  batch_timeout: "500ms"